spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2
  security:
    user:
      name: cognizant
      password: cognizant@123
  application:
    name: /SpringbootapplicationjpaEmployee
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
